language: python
python: 3.5
branches:
  only:
  - master
  - /^v\d.*$/
env:
- TOXENV=py35
- TOXENV=py27
- TOXENV=flake8
install: pip install -U tox
script: tox -e ${TOXENV}
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: potash
  password:
    secure: cEhDRUF3z9iNOCvcb2SrSy9n07WpmdopFRpHN6QDWIZSZB2wJB7U4EolwAWV3jvTi2k9Y/EfK2eg72cptoJ5HciRzE6aG7iGeQS70XLG4FY4WMMB4uCd2cma1/1awSrPwFhJ79AzVJ6HO1569Mq7wSUWJF4J1aHTfniW23GwUfmBbk1inf/4MjGfM7AKCPb9uvz2YC8qJ8s/b24/W4ndCkE1z0KJdA2VDMq2TE8GXMDYBg2Fk0lIA9H1t2Zh3r+1kyhYh3D2CUAk3FHyGxocKBhIrWRjM7ntI8Kqt35AqUzu+69qA5J7Hu6YccLpZXebvm/Hxj6CLJpo2elQ1DhHKQNwLm5m5g/z+lX9cQU2jRZSjheF1UE1ACds7DL+Z/kbzU1HgW6gYoPdULIH3BL9WtHT9xf6vX/rQbbo68eL6XqF92VOVcEaKUicupYINtSsExUsEBBlW8mmx1gAPDKPY2Xo694jOl+yypT24wWf1XchLCKC17Calrup/LBn5C14XisJxZimfIMGmRBCkunj1WkU8Im3XwkBRx7r6KZGeFMODyjwOmuLTHEquU8TiwNyAYO4SiYLjBBD6JWSjae+6cRQNhIHO5w+RXPNcgJ2JvC2qzrrFivsPVB+IipgzT0SvPYuNrAgRGx3+DOFQr6MerYMjfY+3YGtYkWDz3uMkfg=
on:
  tags: true
  branch: master
  repo: dssg/drain
  condition: $TOXENV == py27
